[build-system]
requires = [
    "scikit-build-core>=0.10",
    "torch",
    "torchcodec~=0.10.0"
]
build-backend = "scikit_build_core.build"

[project]
name = "torchcodec-xpu"
description = "Intel extension for torchcodec"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
    { name = "Dmitry Rogozhkin", email = "dmitry.v.rogozhkin@intel.com" },
]
dynamic = ["version"]
dependencies = [
    "torchcodec~=0.10.0"
]

[project.urls]
GitHub = "https://github.com/dvrogozh/torchcodec-xpu"

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "version.txt"
regex = "^v?(?P<value>[0-9a-zA-Z.+-_]+)"

[project.optional-dependencies]
test = [
    "numpy",
    "pytest",
    "ruff",
    "torcheval",
]

[tool.ruff.lint]
    select = ["E", "F", "I"]
    ignore = ["E501", "F403", "F405"]
