[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "torchcodec-xpu"
description = "Intel extension for torchcodec"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
    { name = "Dmitry Rogozhkin", email = "dmitry.v.rogozhkin@intel.com" },
]
dynamic = ["version"]

[project.urls]
GitHub = "https://github.com/dvrogozh/torchcodec-xpu"

[project.entry-points.'torchcodec.backends']
device_backend = 'torchcodec_xpu:load_torchcodec_xpu_shared_library'

[tool.setuptools.dynamic]
version = {file = "version.txt"}

[project.optional-dependencies]
test = [
    "numpy",
    "pytest",
    "ruff",
    "torcheval",
]

[tool.ruff.lint]
    select = ["E", "F", "I"]
    ignore = ["E501", "F403", "F405"]
